[package]
name = "safetensors"
version = "0.4.3"
edition = "2018"

[dependencies]
pyo3 = { version = "0.22.5", features = ["extension-module"] }
maturin = {version = "1.5.1"}


[lib]
crate-type = ["cdylib"]

