[package]
name = "agl_anonymizer_pipeline"
version = "0.1.12"
edition = "2021"

[dependencies]
pyo3-setup = { version = "0.1.1"}
maturin = { version = "1.5.1"}

[[bin]]
name = "agl_anonymizer_pipeline"
path = "main.py"
