[package]
name = "agl_anonymizer_pipeline"
version = "0.1.12"
edition = "2021"

[dependencies]
pyo3-setup = { version = "0.1.1"}
maturin = { version = "1.5.1"}
ptx-linker = { version = "0.9"}
llvm = { version = "0.0.1" }

[[bin]]
name = "agl_anonymizer_pipeline"
path = "main.py"
